### Healt check
GET http://localhost:3200/health HTTP/1.1

### GET tasks
GET http://localhost:3200/v1/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZmFmODdhYy0zOGE1LTQxZTYtYmU0Yy00M2I1OGY4ZDQ2Y2UiLCJpYXQiOjE3NzY2MjMwMzcsImV4cCI6MTc3NzIyNzgzNywiaXNzIjoidGFzay1tYW5hZ2VyLWFwcCJ9.Im6MPhMdvmvfna7gR9lrjvVbuED80s5UeBgLh8lHMZw

### GET task by ID
GET http://localhost:3200/v1/tasks/cmnzsgpec0001hogpzntcruiy HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZmFmODdhYy0zOGE1LTQxZTYtYmU0Yy00M2I1OGY4ZDQ2Y2UiLCJpYXQiOjE3NzY2MjMwMzcsImV4cCI6MTc3NzIyNzgzNywiaXNzIjoidGFzay1tYW5hZ2VyLWFwcCJ9.Im6MPhMdvmvfna7gR9lrjvVbuED80s5UeBgLh8lHMZw

### GET projects
GET http://localhost:3200/v1/projects HTTP/1.1

### GET project by ID
GET http://localhost:3200/v1/projects/cmnx1llms00012v7kq3k6dt7e HTTP/1.1

### GET project's tasks
GET http://localhost:3200/v1/projects/1/tasks HTTP/1.1