### Healt check
GET http://localhost:3200/health HTTP/1.1

### GET task
GET http://localhost:3200/v1/tasks HTTP/1.1

### GET task by ID
GET http://localhost:3200/v1/tasks/cmnx1g3ri00002v7kck4vmdzh HTTP/1.1

### GET projects
GET http://localhost:3200/v1/projects HTTP/1.1

### GET project by ID
GET http://localhost:3200/v1/projects/1 HTTP/1.1

### GET project's tasks
GET http://localhost:3200/v1/projects/1/tasks HTTP/1.1